#!/usr/bin/env bash
#This script uses an if else statement to print certain outputs on certain lines

i=0
while [ $i -lt 10 ]
do
	i=$((i+1))
	if [[ $i == 4 ]]; then
		echo "bad luck"
	elif [[ $i == 8 ]]; then
		echo "good luck"
	else
		echo "Holberton School"
	fi
done
